Repository pydantic/pydantic-core, pull requests merged in 2023-07, with the labels that each got.

#723 allow typing-extensions-4.7.0+ on pypy3.9+
  pyproject.toml
Labels: ready for review

#726 Add benchmark for field validator functions
  tests/benchmarks/test_micro_benchmarks.py
Labels: ready for review

#629 try testing and building for 3.12
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  pyproject.toml
  tests/benchmarks/test_micro_benchmarks.py
  tests/validators/test_date.py
  tests/validators/test_datetime.py
Labels: Full Build

#713 basic tidy-ups to core_schema.py
  python/pydantic_core/core_schema.py
Labels: ready for review

#727 Don't warn on missing fields if exclude_* are used
  src/serializers/fields.rs
Labels: ready for review

#678 build with PGO on x86_64 ubuntu and windows
  .github/workflows/ci.yml
  .github/workflows/codspeed.yml
Labels: Full Build, ready for review

#733 build pypy3.10 wheels on PGO platforms
  .github/workflows/ci.yml
Labels: ready for review

#734 Bump version to 2.1.0
  Cargo.lock
  Cargo.toml
Labels: ready for review

#735 Update python3-dll-a to 0.2.8
  Cargo.lock
  Cargo.toml
Labels: ready for review

#743 use __new__ in .pyi for Rust types
  python/pydantic_core/_pydantic_core.pyi
Labels: ready for review

#746 Properly truncate characters when splitting up strings in error repr
  src/errors/validation_exception.rs
  tests/test_misc.py
Labels: ready for review

#741 add build-pgo make target
  .github/workflows/ci.yml
  Makefile
Labels: ready for review

#748 remove pydantic V1 comparisons from benchmark suite
  .github/workflows/ci.yml
  tests/benchmarks/README.md
  tests/benchmarks/complete_schema.py
  tests/benchmarks/test_complete_benchmark.py
  tests/benchmarks/test_micro_benchmarks.py
  tests/benchmarks/test_serialization_micro.py
  tests/requirements.txt
Labels: ready for review

#749 add `build_info` to `_pydantic_core`
  python/pydantic_core/_pydantic_core.pyi
  src/lib.rs
  tests/test_misc.py
Labels: ready for review

#757 fix pypy tests on windows
  src/recursion_guard.rs
  tests/benchmarks/test_micro_benchmarks.py
Labels: Full Build

#759 use pydantic's version in error messages
  src/errors/validation_exception.rs
  src/lib.rs
  tests/conftest.py
  tests/test_build.py
  tests/test_errors.py
  tests/test_misc.py
  tests/validators/test_arguments.py
  tests/validators/test_bool.py
  tests/validators/test_definitions_recursive.py
  tests/validators/test_int.py
  tests/validators/test_model_fields.py
  tests/validators/test_typed_dict.py
  tests/validators/test_union.py
Labels: ready for review

#764 fix borrow error when serializing recursive models
  src/serializers/infer.rs
  src/serializers/mod.rs
  src/serializers/shared.rs
  tests/serializers/test_functions.py
  tests/serializers/test_model.py
Labels: ready for review

#762 Update speedate and truncate microseconds by default
  Cargo.lock
  Cargo.toml
  python/pydantic_core/core_schema.py
  src/input/datetime.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/serializers/config.rs
  src/serializers/infer.rs
  src/serializers/mod.rs
  src/serializers/type_serializers/mod.rs
  src/validators/date.rs
  src/validators/datetime.rs
  src/validators/time.rs
  src/validators/timedelta.rs
  tests/test_schema_functions.py
  tests/validators/test_time.py
Labels: ready for review

#768 Consider `exclude_none` in `computed_field` serialization
  src/serializers/computed_fields.rs
  tests/serializers/test_model.py
Labels: ready for review

#709 Type validation context as `dict[str, Any] | None`
  python/pydantic_core/_pydantic_core.pyi
Labels: awaiting author revision

#769 Update speedate to 0.11.0
  Cargo.lock
  Cargo.toml
  src/input/datetime.rs
  src/validators/date.rs
  tests/test_hypothesis.py
  tests/validators/test_datetime.py
  tests/validators/test_time.py
Labels: ready for review

#770 Make TzInfo picklable
  python/pydantic_core/_pydantic_core.pyi
  src/input/datetime.rs
  src/input/mod.rs
  src/lib.rs
  tests/validators/test_datetime.py
Labels: ready for review

#782 set up stable Rust toolchain on all rust builds
  .github/workflows/ci.yml
Labels: ready for review

#781 fix type annotations for Url & MultiHostUrl build
  python/pydantic_core/_pydantic_core.pyi
Labels: ready for review

#776 Fix ValidationInfo repr
  src/validators/function.rs
  tests/validators/test_dataclasses.py
  tests/validators/test_function.py
  tests/validators/test_model.py
  tests/validators/test_model_root.py
Labels: ready for review

#767 run pydantic tests as an allowed-to-fail job
  .github/workflows/ci.yml
Labels: ready for review

#783 🐛 Fix handling of bool literals
  src/serializers/type_serializers/literal.rs
  tests/serializers/test_literal.py
  tests/serializers/test_union.py
Labels: ready for review

#765 reject is_instance inputs based on their type, not the mode
  src/validators/is_instance.rs
  tests/validators/test_is_instance.py
Labels: ready for review

#789 correct name of "AssignmentValidatorCallable"
  src/validators/function.rs
Labels: ready for review

#788 Always convert str subclasses to str
  src/input/input_python.rs
  tests/validators/test_string.py
Labels: ready for review

#794 Remove patch version number from error link
  src/errors/validation_exception.rs
  tests/conftest.py
Labels: ready for review

#791 add weekly dependabot configuration
  .github/dependabot.yml
Labels: ready for review

#793 add profiling make target and instructions
  Makefile
  README.md
Labels: ready for review

#772 Add uuid validator
  Cargo.lock
  Cargo.toml
  python/pydantic_core/core_schema.py
  src/errors/types.rs
  src/input/return_enums.rs
  src/serializers/infer.rs
  src/serializers/ob_type.rs
  src/serializers/shared.rs
  src/serializers/type_serializers/mod.rs
  src/serializers/type_serializers/uuid.rs
  src/validators/mod.rs
  src/validators/uuid.rs
  tests/benchmarks/complete_schema.py
  tests/benchmarks/test_complete_benchmark.py
  tests/benchmarks/test_micro_benchmarks.py
  tests/benchmarks/test_serialization_micro.py
  tests/serializers/test_uuid.py
  tests/test_errors.py
  tests/test_schema_functions.py
  tests/validators/test_uuid.py
Labels: ready for review

#817 use github continue-on-error to avoid red CI with test-pydantic-integration
  .github/workflows/ci.yml
Labels: ready for review

#809 Fix error context type annotations
  python/pydantic_core/__init__.py
  python/pydantic_core/_pydantic_core.pyi
  python/pydantic_core/core_schema.py
  tests/test_errors.py
Labels: ready for review

#832 ruff: ignore E501
  pyproject.toml
  tests/test_misc.py
  tests/validators/test_float.py
  tests/validators/test_timedelta.py
Labels: ready for review
