Repository pydantic/pydantic-core, pull requests merged in 2023-08, with the labels that each got.

#826 optimize Python float validation
  src/input/input_python.rs
  src/input/return_enums.rs
  src/validators/float.rs
Labels: ready for review

#839 Fix PydanticKnownError user context handling issues
  src/errors/mod.rs
  src/errors/types.rs
  src/errors/validation_exception.rs
  src/errors/value_exception.rs
  src/input/datetime.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/return_enums.rs
  src/input/shared.rs
  src/validators/arguments.rs
  src/validators/bytes.rs
  src/validators/callable.rs
  src/validators/dataclass.rs
  src/validators/date.rs
  src/validators/datetime.rs
  src/validators/definitions.rs
  src/validators/float.rs
  src/validators/function.rs
  src/validators/generator.rs
  src/validators/int.rs
  src/validators/is_instance.rs
  src/validators/is_subclass.rs
  src/validators/list.rs
  src/validators/literal.rs
  src/validators/model.rs
  src/validators/model_fields.rs
  src/validators/none.rs
  src/validators/string.rs
  src/validators/time.rs
  src/validators/timedelta.rs
  src/validators/tuple.rs
  src/validators/typed_dict.rs
  src/validators/union.rs
  src/validators/url.rs
  src/validators/uuid.rs
  tests/test_errors.py
Labels: ready for review

#852 fix: cargo include
  Cargo.toml
Labels: ready for review

#866 special case serialization for int as input to float
  src/serializers/ob_type.rs
  tests/serializers/test_simple.py
Labels: ready for review

#763 add decimal validator
  generate_self_schema.py
  python/pydantic_core/core_schema.py
  src/errors/mod.rs
  src/errors/types.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/serializers/shared.rs
  src/serializers/type_serializers/decimal.rs
  src/serializers/type_serializers/mod.rs
  src/validators/decimal.rs
  src/validators/mod.rs
  tests/benchmarks/complete_schema.py
  tests/benchmarks/test_complete_benchmark.py
  tests/benchmarks/test_micro_benchmarks.py
  tests/serializers/test_decimal.py
  tests/test_errors.py
  tests/test_schema_functions.py
  tests/validators/test_decimal.py
Labels: ready for review

#868 Allow parsing numbers w/ underscores (e.g. 1_000) from strings
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/shared.rs
  tests/validators/test_float.py
  tests/validators/test_int.py
Labels: awaiting author revision

#881 custom behaviour for timedelta subclasses
  src/input/datetime.rs
  src/input/input_python.rs
  src/input/mod.rs
  src/serializers/config.rs
  src/serializers/infer.rs
  src/serializers/type_serializers/timedelta.rs
  src/validators/timedelta.rs
  tests/requirements.txt
  tests/serializers/test_timedelta.py
  tests/validators/test_timedelta.py
Labels: ready for review

#841 Support manually specifying case labels for union validators
  generate_self_schema.py
  python/pydantic_core/core_schema.py
  src/serializers/type_serializers/union.rs
  src/validators/union.rs
  tests/serializers/test_union.py
  tests/validators/test_union.py
Labels: ready for review

#860 fix serialization of subclasses
  src/serializers/infer.rs
  src/serializers/ob_type.rs
  src/serializers/type_serializers/dataclass.rs
  src/serializers/type_serializers/decimal.rs
  src/serializers/type_serializers/model.rs
  src/serializers/type_serializers/nullable.rs
  tests/requirements.txt
  tests/serializers/test_any.py
  tests/serializers/test_simple.py
  tests/test_json.py
  wasm-preview/worker.js
Labels: ready for review

#889 add `left_to_right` union mode
  Cargo.lock
  Cargo.toml
  python/pydantic_core/core_schema.py
  src/validators/dataclass.rs
  src/validators/model.rs
  src/validators/union.rs
  src/validators/validation_state.rs
  tests/validators/test_union.py
Labels: ready for review

#895 don't install pytest-codspeed on non x86_64 machines
  tests/requirements.txt
Labels: ready for review

#894 add some missing pypy builds for macos
  .github/workflows/ci.yml
Labels: Full Build, ready for review

#893 disable mimalloc on manylinux cross-compiles
  .github/workflows/ci.yml
Labels: Full Build, ready for review

#915 Convert datetime error message to human friendly message
  src/validators/timedelta.rs
  tests/validators/test_timedelta.py
Labels: ready for review

#919 fix big int subclass extraction
  src/input/input_python.rs
  src/input/return_enums.rs
  tests/validators/test_int.py
Labels: ready for review

#911 Allow customizing serialization of extras
  python/pydantic_core/core_schema.py
  src/serializers/fields.rs
  src/serializers/type_serializers/dataclass.rs
  src/serializers/type_serializers/model.rs
  src/serializers/type_serializers/tuple.rs
  src/serializers/type_serializers/typed_dict.rs
  src/validators/dataclass.rs
  src/validators/model_fields.rs
  src/validators/tuple.rs
  src/validators/typed_dict.rs
  tests/benchmarks/test_micro_benchmarks.py
  tests/serializers/test_dataclasses.py
  tests/serializers/test_list_tuple.py
  tests/serializers/test_model.py
  tests/serializers/test_typed_dict.py
  tests/test_json.py
  tests/validators/test_model_fields.py
  tests/validators/test_tuple.py
  tests/validators/test_typed_dict.py
  tests/validators/test_with_default.py
Labels: ready for review

#902 Fix max length error on conlist with type int
  src/input/return_enums.rs
  tests/validators/test_list.py
Labels: ready for review

#922 snipe off some unsafe code
  src/errors/validation_exception.rs
  src/input/input_python.rs
  src/input/return_enums.rs
  src/serializers/infer.rs
  src/serializers/ob_type.rs
Labels: ready for review
