Repository pydantic/pydantic-core, pull requests merged in 2023-06, with the labels that each got.

#655 Allow non-scalar values as tagged union keys
  generate_self_schema.py
  pydantic_core/core_schema.py
  src/input/input_abstract.rs
  src/input/input_python.rs
  src/lookup_key.rs
  src/validators/literal.rs
  src/validators/union.rs
  tests/validators/test_tagged_union.py
Labels: ready for review

#661 🐛 Fix `__pydantic_fields_set__` behavior on `RootModel`
  Cargo.lock
  pydantic_core/__init__.py
  pydantic_core/_pydantic_core.pyi
  pydantic_core/core_schema.py
  src/argument_markers.rs
  src/lib.rs
  src/validators/model.rs
  src/validators/with_default.rs
  tests/test_misc.py
  tests/validators/test_model_root.py
Labels: ready for review

#664 Docstring fixes for core_schema.py
  pydantic_core/core_schema.py
Labels: documentation

#677 correct MultiHostUrl __repr__
  src/url.rs
  tests/validators/test_url.py
Labels: ready for review

#676 make Url and MultiHostUrl pickleable
  src/url.rs
  tests/serializers/test_url.py
Labels: ready for review

#679 🐛 Fix crash on serializing a union of RootModel and BaseModel
  src/serializers/type_serializers/model.rs
  tests/serializers/test_model_root.py
Labels: ready for review

#682 fix windows build crash on generate_self_schema.py
  .github/workflows/ci.yml
  build.rs
Labels: Full Build

#684 expand allowed errors from hypothesis test for url parsing
  tests/test_hypothesis.py
Labels: ready for review

#687 bump maturin version to 1.0
  .github/workflows/ci.yml
  pyproject.toml
Labels: ready for review

#688 add PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#690 🐛 Raise `PydanticSerializationUnexpectedValue` in root model serializer only if strict check is enabled
  src/serializers/type_serializers/model.rs
  tests/serializers/test_model_root.py
Labels: ready for review

#693 🚸 Expose `PydanticUndefinedType`
  pydantic_core/__init__.py
  pydantic_core/_pydantic_core.pyi
  src/argument_markers.rs
  src/lib.rs
  src/validators/model.rs
  src/validators/with_default.rs
Labels: ready for review

#699 🔧 Add `assignees` list to the hooky config
  pyproject.toml
Labels: ready for review

#701 reconcile _pydantic_core.pyi against the Rust implementation
  pydantic_core/__init__.py
  pydantic_core/_pydantic_core.pyi
  src/errors/types.rs
  src/errors/validation_exception.rs
  src/serializers/config.rs
  src/serializers/extra.rs
  src/serializers/mod.rs
Labels: awaiting author revision

#704 Remove unused bool error
  pydantic_core/core_schema.py
  src/errors/types.rs
  tests/test_errors.py
Labels: ready for review

#705 move pydantic_core -> python/pydantic_core
  .cargo/config.toml
  .github/workflows/ci.yml
  .github/workflows/codspeed.yml
  .gitignore
  Cargo.toml
  Makefile
  generate_self_schema.py
  pyproject.toml
  python/pydantic_core/__init__.py
  python/pydantic_core/_pydantic_core.pyi
  python/pydantic_core/core_schema.py
  python/pydantic_core/py.typed
  src/lib.rs
  tests/test_docstrings.py
  tests/test_errors.py
  tests/test_misc.py
Labels: Full Build, ready for review

#708 small cleanups after move to python/ source dir
  README.md
  build.rs
Labels: ready for review

#702 run stubtest on _pydantic_core.pyi
  .github/workflows/ci.yml
  .mypy-stubtest-allowlist
  Makefile
  python/pydantic_core/__init__.py
  python/pydantic_core/_pydantic_core.pyi
  python/pydantic_core/core_schema.py
  src/argument_markers.rs
  src/url.rs
  src/validators/mod.rs
  tests/requirements-linting.txt
Labels: ready for review

#691 Add eitherfloat
  src/errors/types.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/mod.rs
  src/input/return_enums.rs
  src/validators/float.rs
  tests/test_errors.py
  tests/test_json.py
  tests/test_misc.py
  tests/validators/test_float.py
Labels: ready for review

#710 Use `from __future__ import annotations` instead of string type hints in `python/pydantic_core/_pydantic_core.pyi`
  python/pydantic_core/_pydantic_core.pyi
Labels: ready for review

#714 PYD-137: Implement PydanticUseDefault error
  .mypy-stubtest-allowlist
  python/pydantic_core/__init__.py
  python/pydantic_core/_pydantic_core.pyi
  src/build_tools.rs
  src/errors/line_error.rs
  src/errors/mod.rs
  src/errors/validation_exception.rs
  src/errors/value_exception.rs
  src/lib.rs
  src/validators/function.rs
  src/validators/mod.rs
  src/validators/with_default.rs
  tests/validators/test_with_default.py
Labels: ready for review

#694 Add faster int inequality
  src/errors/types.rs
  src/input/mod.rs
  src/input/return_enums.rs
  src/validators/int.rs
Labels: ready for review

#720 prepare to release v2.0.0
  Cargo.lock
  Cargo.toml
Labels: Full Build
