Repository pydantic/pydantic-core, pull requests merged in 2023-05, with the labels that each got.

#582 🐛 Deepcopy mutable defaults
  src/validators/with_default.rs
  tests/validators/test_with_default.py
Labels: ready for review

#588 Uprev to 0.29.0
  Cargo.lock
  Cargo.toml
Labels: ready for review

#592 RootModel
  pydantic_core/core_schema.py
  src/validators/model.rs
  tests/benchmarks/test_micro_benchmarks.py
  tests/validators/test_model_init.py
  tests/validators/test_model_root.py
Labels: ready for review

#598 Add JsonOrPython validator and serializer
  pydantic_core/_pydantic_core.pyi
  pydantic_core/core_schema.py
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/mod.rs
  src/input/parse_json.rs
  src/serializers/shared.rs
  src/serializers/type_serializers/json_or_python.rs
  src/serializers/type_serializers/mod.rs
  src/validators/dataclass.rs
  src/validators/function.rs
  src/validators/generator.rs
  src/validators/is_instance.rs
  src/validators/json_or_python.rs
  src/validators/mod.rs
  src/validators/model.rs
  tests/benchmarks/test_micro_benchmarks.py
  tests/conftest.py
  tests/serializers/test_json_or_python.py
  tests/test_isinstance.py
  tests/test_schema_functions.py
  tests/validators/test_callable.py
  tests/validators/test_function.py
  tests/validators/test_is_instance.py
  tests/validators/test_json_or_python.py
  tests/validators/test_literal.py
  tests/validators/test_model_init.py
Labels: ready for review

#601 Make ValidationError constructor a non-init method
  pydantic_core/_pydantic_core.pyi
  src/errors/validation_exception.rs
  tests/test_errors.py
Labels: ready for review

#613 ✨ Implement root model serialization
  src/serializers/type_serializers/function.rs
  src/serializers/type_serializers/model.rs
  tests/serializers/test_model.py
  tests/serializers/test_model_root.py
  tests/validators/test_model_root.py
Labels: ready for review

#621 Upgrade maturin to 0.15
  .github/workflows/ci.yml
  pyproject.toml
Labels: Full Build

#627 Support negative indices in serializer include/exclude
  src/serializers/filter.rs
  src/serializers/infer.rs
  src/serializers/type_serializers/function.rs
  src/serializers/type_serializers/generator.rs
  src/serializers/type_serializers/list.rs
  src/serializers/type_serializers/tuple.rs
  tests/benchmarks/test_serialization_micro.py
  tests/serializers/test_any.py
  tests/serializers/test_generator.py
  tests/serializers/test_list_tuple.py
Labels: ready for review

#617 Add slots to dataclass schema
  pydantic_core/core_schema.py
  src/input/input_abstract.rs
  src/input/input_python.rs
  src/serializers/infer.rs
  src/serializers/shared.rs
  src/serializers/type_serializers/dataclass.rs
  src/serializers/type_serializers/mod.rs
  src/serializers/type_serializers/model.rs
  src/validators/dataclass.rs
  src/validators/model.rs
  tests/serializers/test_any.py
  tests/serializers/test_dataclasses.py
  tests/test_schema_functions.py
  tests/validators/test_dataclasses.py
  tests/validators/test_definitions_recursive.py
Labels: ready for review

#633 Add hide_input to ValidationError
  pydantic_core/_pydantic_core.pyi
  pydantic_core/core_schema.py
  src/build_tools.rs
  src/errors/validation_exception.rs
  src/validators/function.rs
  src/validators/generator.rs
  src/validators/mod.rs
  tests/test_config.py
  tests/test_errors.py
  tests/validators/test_function.py
  tests/validators/test_generator.py
Labels: ready for review

#632 fix for model subclass serialization in unions
  src/serializers/fields.rs
  src/serializers/type_serializers/model.rs
  tests/serializers/test_union.py
Labels: ready for review

#634 Use `PyInt` for inequality and multiple of checks
  Cargo.lock
  Cargo.toml
  pydantic_core/core_schema.py
  src/errors/types.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/parse_json.rs
  src/input/return_enums.rs
  src/input/shared.rs
  src/validators/int.rs
  src/validators/literal.rs
  src/validators/union.rs
  tests/benchmarks/test_micro_benchmarks.py
  tests/test_errors.py
  tests/validators/test_int.py
Labels: ready for review

#637 Add error messages for json
  src/errors/types.rs
  tests/validators/test_dataclasses.py
  tests/validators/test_dict.py
  tests/validators/test_frozenset.py
  tests/validators/test_generator.py
  tests/validators/test_model_fields.py
  tests/validators/test_set.py
  tests/validators/test_tagged_union.py
  tests/validators/test_timedelta.py
  tests/validators/test_tuple.py
Labels: awaiting author revision

#643 Add SchemaValidator.get_default_value()
  pydantic_core/__init__.py
  pydantic_core/_pydantic_core.pyi
  src/lib.rs
  src/validators/mod.rs
  tests/validators/test_with_default.py
Labels: awaiting author revision

#645 Add CoreConfig to TypedDict
  pydantic_core/core_schema.py
  src/validators/typed_dict.rs
  tests/validators/test_function.py
  tests/validators/test_typed_dict.py
  tests/validators/test_with_default.py
Labels: ready for review

#647 remove strict checks from models directly
  src/validators/model.rs
  tests/validators/test_model.py
Labels: ready for review

#646 Serialization return schema
  pydantic_core/core_schema.py
  src/serializers/type_serializers/function.rs
  src/serializers/type_serializers/mod.rs
  tests/benchmarks/test_serialization_micro.py
  tests/serializers/test_functions.py
  tests/test_schema_functions.py
  tests/test_typing.py
Labels: ready for review

#651 New speedate
  Cargo.lock
  Cargo.toml
  src/input/datetime.rs
  src/serializers/type_serializers/datetime_etc.rs
  src/validators/date.rs
  src/validators/datetime.rs
  tests/validators/test_date.py
  tests/validators/test_datetime.py
  tests/validators/test_time.py
Labels: ready for review

#652 Move dataclass config onto dataclass schema
  pydantic_core/core_schema.py
  src/validators/dataclass.rs
  tests/validators/test_dataclasses.py
  tests/validators/test_definitions_recursive.py
Labels: ready for review
