Repository pydantic/pydantic-core, pull requests merged in 2023-11, with the labels that each got.

#1050 fix: proper pluralization in validation error messages
  src/errors/types.rs
  tests/test_errors.py
Labels: ready for review

#1059 reduce dependabot frequency
  .github/dependabot.yml
Labels: ready for review

#1063 PGO build for MacOS M1
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/input/input_json.rs
Labels: Full Build

#1054 run pydantic integration tests with lax xfail
  .github/workflows/ci.yml
Labels: ready for review

#867 replace ultra_strict with new union implementation
  src/definitions.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/input_string.rs
  src/input/mod.rs
  src/input/return_enums.rs
  src/validators/any.rs
  src/validators/arguments.rs
  src/validators/bool.rs
  src/validators/bytes.rs
  src/validators/call.rs
  src/validators/callable.rs
  src/validators/chain.rs
  src/validators/custom_error.rs
  src/validators/dataclass.rs
  src/validators/date.rs
  src/validators/datetime.rs
  src/validators/decimal.rs
  src/validators/definitions.rs
  src/validators/dict.rs
  src/validators/float.rs
  src/validators/frozenset.rs
  src/validators/function.rs
  src/validators/generator.rs
  src/validators/int.rs
  src/validators/is_instance.rs
  src/validators/is_subclass.rs
  src/validators/json.rs
  src/validators/json_or_python.rs
  src/validators/lax_or_strict.rs
  src/validators/list.rs
  src/validators/literal.rs
  src/validators/mod.rs
  src/validators/model.rs
  src/validators/model_fields.rs
  src/validators/none.rs
  src/validators/nullable.rs
  src/validators/set.rs
  src/validators/string.rs
  src/validators/time.rs
  src/validators/timedelta.rs
  src/validators/tuple.rs
  src/validators/typed_dict.rs
  src/validators/union.rs
  src/validators/url.rs
  src/validators/uuid.rs
  src/validators/validation_state.rs
  src/validators/with_default.rs
  tests/validators/test_definitions_recursive.py
  tests/validators/test_union.py
Labels: ready for review

#1068 Restore manylinux-compatible PGO builds
  .github/workflows/ci.yml
Labels: Full Build, ready for review

#1072 restore pypy builds for x86_64
  .github/workflows/ci.yml
Labels: Full Build, ready for review

#1076 Fix bug re `custom_init` on members of `Union`
  src/validators/model.rs
  tests/validators/test_model_init.py
Labels: ready for review

#1075 Fix validation of `Literal` from JSON keys when used as `dict` key
  src/validators/literal.rs
  tests/test.rs
Labels: ready for review

#1081 uprev: 2.14.4
  Cargo.lock
  Cargo.toml
Labels: ready for review

#1083 move all clippy lints into `[lints.clippy]` table
  Cargo.toml
  Makefile
Labels: ready for review

#1084 Remove lifetime from errors
  src/errors/line_error.rs
  src/errors/mod.rs
  src/errors/validation_exception.rs
  src/errors/value_exception.rs
  src/input/datetime.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/input_string.rs
  src/input/return_enums.rs
  src/input/shared.rs
  src/lookup_key.rs
  src/validators/any.rs
  src/validators/arguments.rs
  src/validators/bool.rs
  src/validators/bytes.rs
  src/validators/call.rs
  src/validators/callable.rs
  src/validators/chain.rs
  src/validators/custom_error.rs
  src/validators/dataclass.rs
  src/validators/date.rs
  src/validators/datetime.rs
  src/validators/decimal.rs
  src/validators/definitions.rs
  src/validators/dict.rs
  src/validators/float.rs
  src/validators/frozenset.rs
  src/validators/function.rs
  src/validators/generator.rs
  src/validators/int.rs
  src/validators/is_instance.rs
  src/validators/is_subclass.rs
  src/validators/json.rs
  src/validators/json_or_python.rs
  src/validators/lax_or_strict.rs
  src/validators/list.rs
  src/validators/literal.rs
  src/validators/mod.rs
  src/validators/model.rs
  src/validators/model_fields.rs
  src/validators/none.rs
  src/validators/nullable.rs
  src/validators/set.rs
  src/validators/string.rs
  src/validators/time.rs
  src/validators/timedelta.rs
  src/validators/tuple.rs
  src/validators/typed_dict.rs
  src/validators/union.rs
  src/validators/url.rs
  src/validators/uuid.rs
  src/validators/with_default.rs
Labels: ready for review

#1087 Fix typo in is_instance_schema docstring
  python/pydantic_core/core_schema.py
Labels: ready for review

#1086 Don't build dummy objects when populating `ObTypeLookup`
  src/serializers/ob_type.rs
Labels: ready for review

#1088 Remove needless uses of `PyString::intern`
  src/lookup_key.rs
  src/serializers/type_serializers/dataclass.rs
  src/validators/arguments.rs
  src/validators/dataclass.rs
  src/validators/model.rs
  src/validators/model_fields.rs
  src/validators/typed_dict.rs
Labels: ready for review

#1090 Correct deprecation message for general_after_validator_function
  python/pydantic_core/core_schema.py
Labels: ready for review
