Repository pydantic/pydantic-core, pull requests merged in 2024-08, with the labels that each got.

#1308 Validate bytes based on ser_json_bytes
  Cargo.lock
  Cargo.toml
  python/pydantic_core/_pydantic_core.pyi
  python/pydantic_core/core_schema.py
  src/errors/types.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/input_string.rs
  src/lib.rs
  src/serializers/config.rs
  src/serializers/mod.rs
  src/validators/bytes.rs
  src/validators/config.rs
  src/validators/json.rs
  src/validators/mod.rs
  src/validators/uuid.rs
  tests/test_errors.py
  tests/test_json.py
Labels: awaiting author revision

#1393 Revert "use little endian int (#1372)"
  src/serializers/type_serializers/uuid.rs
Labels: Full Build

#1395 Validate base64 standard encoding
  src/validators/config.rs
  tests/test_json.py
Labels: ready for review

#1331 Support complex numbers
  generate_self_schema.py
  python/pydantic_core/core_schema.py
  src/errors/types.rs
  src/input/input_abstract.rs
  src/input/input_json.rs
  src/input/input_python.rs
  src/input/input_string.rs
  src/input/return_enums.rs
  src/serializers/infer.rs
  src/serializers/ob_type.rs
  src/serializers/shared.rs
  src/serializers/type_serializers/complex.rs
  src/serializers/type_serializers/mod.rs
  src/validators/complex.rs
  src/validators/mod.rs
  tests/serializers/test_complex.py
  tests/test_errors.py
  tests/test_schema_functions.py
  tests/validators/test_complex.py
  tests/validators/test_dict.py
Labels: enhancement

#1417 Support `BigInt` serialization for `int` subclasses
  src/serializers/infer.rs
  tests/serializers/test_any.py
Labels: ready for review
