Repository pydantic/pydantic-core, pull requests merged in 2024-10, with the labels that each got.

#1477 ci: add prebuilt musl for armv7
  .github/workflows/ci.yml
Labels: Full Build

#1484 ci: fix for ubuntu 24.04, use Python 3.13 for scripts
  .github/workflows/ci.yml
  .github/workflows/codspeed.yml
Labels: Full Build

#1482 Add `serialization` key to `InvalidSchema`
  python/pydantic_core/core_schema.py
Labels: awaiting author revision

#1413 Allow subclassing ValidationError and PydanticCustomError
  python/pydantic_core/_pydantic_core.pyi
  src/errors/validation_exception.rs
  src/errors/value_exception.rs
  tests/test_custom_errors.py
Labels: ready for review
