Repository pydantic/pydantic-core, pull requests merged in 2024-01, with the labels that each got.

#1129 drop Python 3.7, and PyPy 3.7 and 3.8
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  generate_self_schema.py
  pyproject.toml
Labels: Full Build, ready for review

#1123 Rework `PYDANTIC_ERRORS_OMIT_URL` to `PYDANTIC_ERRORS_INCLUDE_URL`
  python/pydantic_core/_pydantic_core.pyi
  src/errors/validation_exception.rs
  tests/test_errors.py
Labels: ready for review

#865 Add unified tuple validator that can handle "variadic" tuples via PEP-646
  generate_self_schema.py
  python/pydantic_core/core_schema.py
  src/serializers/shared.rs
  src/serializers/type_serializers/tuple.rs
  src/validators/mod.rs
  src/validators/tuple.rs
  src/validators/union.rs
  tests/benchmarks/complete_schema.py
  tests/benchmarks/test_micro_benchmarks.py
  tests/serializers/test_list_tuple.py
  tests/serializers/test_none.py
  tests/test_schema_functions.py
  tests/test_typing.py
  tests/validators/test_definitions_recursive.py
  tests/validators/test_frozenset.py
  tests/validators/test_list.py
  tests/validators/test_set.py
  tests/validators/test_tuple.py
  tests/validators/test_with_default.py
Labels: ready for review

#1132 Use stricter serializer for unions of simple types
  src/serializers/type_serializers/simple.rs
  tests/serializers/test_union.py
Labels: awaiting author revision

#1146 adjust build for upload-artifact-4
  .github/workflows/ci.yml
Labels: Full Build

#1156 improve performance of recursion guard
  src/recursion_guard.rs
  src/serializers/extra.rs
  src/validators/definitions.rs
  tests/serializers/test_any.py
Labels: V3

#1168 fix: 8405 pattern serialization
  src/serializers/infer.rs
  src/serializers/ob_type.rs
  tests/serializers/test_any.py
Labels: ready for review

#1172 fix(uuid): validation from string
  src/validators/uuid.rs
  tests/validators/test_uuid.py
Labels: ready for review
