Repository pydantic/pydantic-core, pull requests merged in 2024-07, with the labels that each got.

#1360 Bump `pytest-examples` to get tests passing with ruff `v0.5.0`
  .github/workflows/ci.yml
  tests/requirements-linting.txt
  tests/requirements.txt
  tests/validators/test_list.py
Labels: dependencies

#1286 Fixes discriminated union bug regression when using enums
  src/serializers/type_serializers/literal.rs
  tests/serializers/test_literal.py
Labels: ready for review

#1349 Fix model field serializer with computed field
  src/serializers/computed_fields.rs
  tests/serializers/test_model.py
Labels: ready for review

#1372 use little endian int
  src/serializers/type_serializers/uuid.rs
Labels: Full Build
