Repository pydantic/pydantic-core, pull requests merged in 2024-09, with the labels that each got.

#1448 Do not require padding when decoding base64 bytes
  src/validators/config.rs
  tests/test_json.py
Labels: ready for review

#1427 feat: add 'millisecond' option to ser_json_timedelta config parameter
  python/pydantic_core/_pydantic_core.pyi
  python/pydantic_core/core_schema.py
  src/input/datetime.rs
  src/serializers/config.rs
  src/serializers/infer.rs
  src/serializers/type_serializers/timedelta.rs
  tests/serializers/test_any.py
  tests/serializers/test_pickling.py
  tests/serializers/test_timedelta.py
  tests/test_garbage_collection.py
Labels: ready for review

#1451 Add support for unpacked `TypedDict` to type hint variadic keyword arguments in `ArgumentsValidator`
  python/pydantic_core/core_schema.py
  src/validators/arguments.rs
  tests/validators/test_arguments.py
Labels: awaiting author revision

#1463 limit windows builds to Rust 1.77 (to keep Windows 7 support)
  .github/workflows/ci.yml
Labels: Full Build
